const Images={
    logo: require('../assets/image/Frame2.png'),
    slideIcon: require('../assets/image/SlideIcon.png'),
    girlLogo: require('../assets/image/GirlLogo.png'),
    circleLogo: require('../assets/image/CircleLogo.png'),
   travelImage: require('../assets/image/TravelImage.png'),
   womann2 : require('../assets/image/Woman2.png'),
   explore1 : require('../assets/image/Explore.png'),
   sailing : require('../assets/image/SailingImage.png'),
   kayaKIng : require('../assets/image/KayaKingImage.png'),
   cottage : require('../assets/image/CottageImage.png'),
   kepulauan : require('../assets/image/KepulauanImage.png'),
   taman : require('../assets/image/TamanImage.png'),
   gunung : require('../assets/image/GunungImage.png'),
   pulau : require('../assets/image/PulauImage.png'),
   tana : require('../assets/image/TanaImage.png'),
   om : require('../assets/image/OmImage.png'),
   message  : require('../assets/image/Message.png'),
   profileWoman: require('../assets/image/Woman3.png'),
   profileVc: require('../assets/image/Profilevc.png'),
   paymentVectorIcon: require('../assets/image/Payment.png'),
   LanguageVectorIcon: require('../assets/image/Language.png'),
   PrivacyVectorIcon: require('../assets/image/Privacy.png'),
  advanceSetting: require('../assets/image/Advance.png'),
  rajaAmpat: require('../assets/image/RajaAmpat.png'),
  sungai: require('../assets/image/Sungai.png'),
  danau: require('../assets/image/Danau.png'),
  air: require('../assets/image/Air.png'),
  rajaAmpatProfile: require('../assets/image/RajaAmpatProfile.png'),
}

export {Images}